version: '3.8'

services:
  redpanda-1:
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.8
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '1'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9092
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda-1:33145
    ports:
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
    networks:
      - Algotrading

  redpanda-2:
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.8
    container_name: redpanda-2
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '2'
      - --seeds
      - redpanda-1:33145
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda-2:29093,OUTSIDE://localhost:9093
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28083,OUTSIDE://0.0.0.0:8083
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda-2:28083,OUTSIDE://localhost:8083
      - --rpc-addr
      - 0.0.0.0:33146
      - --advertise-rpc-addr
      - redpanda-2:33146
    ports:
      - 8083:8083
      - 9093:9093
      - 28083:28083
      - 29093:29093
    networks:
      - Algotrading

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.2.4
    container_name: redpanda-console
    entrypoint: /app/console
    environment:
      CONFIG_FILE_PATH: /tmp/alpaca_config.yml
      KAFKA_BROKERS: "redpanda-1:29092,redpanda-2:29093"
      REDPANDA_ADMIN_API: "http://redpanda-1:9644,http://redpanda-2:9644"
    ports:
      - 8080:8080
    depends_on:
      - redpanda-1
      - redpanda-2
    networks:
      - Algotrading
    volumes:
      - ./config:/etc/redpanda

  jobmanager:
    container_name: jobmanager
    build:
      context: .
      dockerfile: Dockerfile-sql
    ports:
      - 8081:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - Algotrading

  taskmanager:
    container_name: taskmanager
    build:
      context: .
      dockerfile: Dockerfile-sql
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
    networks:
      - Algotrading

  sql-client:
    container_name: sql-client
    build:
      context: .
      dockerfile: Dockerfile-sql
    command:
      - /opt/flink/bin/sql-client.sh
      - embedded
      - -l
      - /opt/sql-client/lib
    depends_on:
      - jobmanager
    environment:
      - FLINK_JOBMANAGER_HOST=jobmanager
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    networks:
      - Algotrading

networks:
  Algotrading:
    driver: bridge
